name: network_kit_lite
description: A Dart package inspired by Moya style for Flutter, providing a clean and maintainable way to consume APIs.
version: 0.1.1
homepage: https://github.com/1989allen126/network_kit_lite
repository: https://github.com/1989allen126/network_kit_lite
issue_tracker: https://github.com/1989allen126/network_kit_lite/issues

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.2
  shared_preferences: ^2.2.1
  sqflite: ^2.3.0
  path: ^1.8.3
  crypto: ^3.0.6
  easy_localization: ^3.0.7
  connectivity_plus: ^6.1.3
  uuid: ^4.5.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  source_gen: ^1.4.0
  build: ^2.4.0
  analyzer: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.25.15
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  http_mock_adapter: ^0.6.0
# flutter:
# assets:
# - assets/config/
# - assets/lang/
